---
- name: download alertmanager
  unarchive:
    src: https://github.com/alertmanager/alertmanager/releases/download/v{{alertmanager_version}}/alertmanager-{{alertmanager_version}}.linux-amd64.tar.gz
    dest: "{{alertmanager_installation_path}}"
    remote_src: yes

- name: create alertmanager user
  user:
    name: alertmanager
    create_home: no
    shell: /bin/false

- name: create etc folder
  file:
    path: /etc/alertmanager
    state: directory
    owner: alertmanager
    group: alertmanager

- name: create var lib folder
  file:
    path: /var/lib/alertmanager
    state: directory
    owner: alertmanager
    group: alertmanager

- name: copy binaries
  copy:
    src:
      - "{{alertmanager_installation_path}}/alertmanager-{{alertmanager_version}}.linux-amd64/alertmanager"
      - "{{alertmanager_installation_path}}/alertmanager-{{alertmanager_version}}.linux-amd64/amtool"
    dest: /usr/local/bin/
    owner: alertmanager
    group: alertmanager

- name: create config file from template
  template:
    src: templates/alertmanager.yml.j2
    dest: /etc/alertmanager/alertmanager.yml

- name: create service file from template
  template:
    src: templates/alertmanager.service.j2
    dest: /etc/systemd/system/alertmanager.service

- name: alertmanager service started and enabled
  systemd:
    name: alertmanager
    state: started
    enabled: yes
    daemon_reload: yes
